name: card_club
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  adobe_xd: ^2.0.0+1
  pin_code_fields: ^7.3.0
  table_calendar: ^3.0.3
  syncfusion_flutter_datepicker: ^19.1.55-beta
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  google_sign_in: ^5.2.2
  flutter_login_facebook:
  firebase_database: ^9.0.5
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_messaging:
  cloud_firestore: ^3.1.6
  flutter_signin_button: ^2.0.0
  dotted_border: ^2.0.0+1
  image_painter: ^0.4.4+1
  stick_it: ^1.0.0+2
  flutter_colorpicker: ^1.0.2
  flutter_facebook_auth: ^3.5.7
  image_picker: ^0.8.4+4
  get: ^4.5.1
  get_storage:  #  for get storage
  weekly_date_picker: ^1.3.0
  dotted_line: ^3.1.0
  google_nav_bar: ^5.0.5
  timeline_tile: ^2.0.0
  color_thief_flutter: ^1.0.2
  snapping_sheet: ^3.1.0
  provider: ^5.0.0
  internet_connection_checker: ^0.0.1+3
  sizer: ^2.0.15
  flutter_slidable: ^1.2.0
  flutter_keyboard_visibility: ^5.1.1
  expandable_widgets: ^1.0.2
  custom_pop_up_menu: ^1.2.3+1
  google_fonts: ^2.3.1
  screenshot: ^1.2.3
  lottie: ^1.2.2
  flutter_local_notifications: ^9.3.2
  flutter_stripe: ^2.2.0
  phonenumbers: ^1.1.0
  image_cacheing: ^0.0.2
  pay: ^1.0.1
  image_gallery_saver:
  image_stack: ^2.1.1
  flutter_contacts: ^1.1.3
  carousel_slider: ^4.0.0
  pdf: ^3.1.0
  # save file
  path_provider: ^2.0.1
  # open pdf document
  open_file: ^3.2.1
  dio: ^4.0.6
  syncfusion_flutter_pdf:
  shared_preferences: ^2.0.13
  share_plus: ^4.0.3








dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/
    - assets/
    - assets/icons/
    - assets/animation/


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add_cont assets to your application, add_cont an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add_cont custom fonts to your application, add_cont a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Montserrat
        fonts:
          - asset: fonts/Montserrat-SemiBold.ttf
          - asset: fonts/Montserrat-Regular.ttf
      - family: arial
        fonts:
          - asset: assets/fonts/arial.ttf
      - family: Zuume
        fonts:
          - asset: assets/fonts/Zuume_bold.ttf
          - asset: assets/fonts/Zuume_regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
